<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-EGH5GRK4" ignored="0" name="登录接口" tests="5" failures="4" timestamp="23 八月 2020 04:14:19 GMT" time="0.785" errors="0">
  <testcase name="test" time="0.129" classname="com.api.cases.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.LoginCase.test(LoginCase.java:44)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.096" classname="com.api.cases.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.LoginCase.test(LoginCase.java:44)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.114" classname="com.api.cases.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.LoginCase.test(LoginCase.java:44)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.167" classname="com.api.cases.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.LoginCase.test(LoginCase.java:44)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.168" classname="com.api.cases.LoginCase"/>
</testsuite> <!-- 登录接口 -->
